const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={canvas:$('#canvas'),overlay:$('#overlay'),stage:$('#stage'),viewport:$('#viewport'),empty:$('#emptyState'),panel:$('#panel'),first:$('#firstInput'),file:$('#fileInput'),zoom:$('#zoomText'),fit:$('#fitBtn'),thickness:$('#thickness'),spread:$('#spread'),smooth:$('#smooth'),opacity:$('#opacity'),thicknessOut:$('#thicknessOut'),spreadOut:$('#spreadOut'),smoothOut:$('#smoothOut'),opacityOut:$('#opacityOut'),status:$('#status'),confirmLine:$('#confirmLineBtn'),undoPoint:$('#undoPointBtn'),clearPath:$('#clearPathBtn'),applyPath:$('#applyPathBtn'),undo:$('#undoBtn'),redo:$('#redoBtn'),floatUndo:$('#floatUndo'),floatRedo:$('#floatRedo'),reset:$('#resetBtn'),save:$('#saveBtn'),toast:$('#toast'),help:$('#helpDialog'),helpBtn:$('#helpBtn'),closeHelp:$('#closeHelp')};
const ctx=el.canvas.getContext('2d',{willReadFrequently:true}),ox=el.overlay.getContext('2d');
const isiOS=/iPhone|iPad|iPod/i.test(navigator.userAgent),MAX_DIM=isiOS?2048:3072,MAX_HISTORY=isiOS?3:6;
const state={tool:'line',scale:1,tx:0,ty:0,pointers:new Map(),gesture:null,drawing:false,lastClient:null,original:null,undo:[],redo:[],fileName:'image',line:[],lineConfirmed:false,path:[]};
function say(t){el.toast.textContent=t;el.toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>el.toast.classList.remove('show'),1600)}
function sync(){el.thicknessOut.value=`${el.thickness.value}px`;el.spreadOut.value=`${el.spread.value}%`;el.smoothOut.value=`${el.smooth.value}%`;el.opacityOut.value=`${el.opacity.value}%`}
[el.thickness,el.spread,el.smooth,el.opacity].forEach(x=>x.addEventListener('input',sync));sync();
async function loadFile(file){if(!file||!file.type.startsWith('image/'))return;try{const bmp=await createImageBitmap(file),s=Math.min(1,MAX_DIM/Math.max(bmp.width,bmp.height));el.canvas.width=el.overlay.width=Math.max(1,Math.round(bmp.width*s));el.canvas.height=el.overlay.height=Math.max(1,Math.round(bmp.height*s));ctx.clearRect(0,0,el.canvas.width,el.canvas.height);ctx.drawImage(bmp,0,0,el.canvas.width,el.canvas.height);bmp.close();state.original=ctx.getImageData(0,0,el.canvas.width,el.canvas.height);state.undo=[];state.redo=[];state.line=[];state.path=[];state.lineConfirmed=false;state.fileName=(file.name||'image').replace(/\.[^.]+$/,'');el.empty.classList.add('hidden');el.viewport.classList.remove('hidden');el.panel.classList.remove('hidden');updateHistory();drawOverlay();requestAnimationFrame(fitView);say('사진을 불러왔습니다')}catch{say('사진을 불러오지 못했습니다')}}
[el.first,el.file].forEach(i=>i.addEventListener('change',e=>loadFile(e.target.files[0])));
function fitView(){const r=el.viewport.getBoundingClientRect(),p=20;state.scale=Math.max(.05,Math.min(8,Math.min((r.width-p*2)/el.canvas.width,(r.height-p*2)/el.canvas.height)));state.tx=(r.width-el.canvas.width*state.scale)/2;state.ty=(r.height-el.canvas.height*state.scale)/2;applyTransform()}
function applyTransform(){el.stage.style.transform=`translate(${state.tx}px,${state.ty}px) scale(${state.scale})`;el.zoom.firstChild.textContent=`${Math.round(state.scale*100)}% `}
el.fit.onclick=fitView;window.addEventListener('resize',()=>state.original&&fitView());
function point(cx,cy){const r=el.viewport.getBoundingClientRect();return{x:(cx-r.left-state.tx)/state.scale,y:(cy-r.top-state.ty)/state.scale}}
function inside(p){return p.x>=0&&p.y>=0&&p.x<el.canvas.width&&p.y<el.canvas.height}
function snapshot(){state.undo.push(ctx.getImageData(0,0,el.canvas.width,el.canvas.height));if(state.undo.length>MAX_HISTORY)state.undo.shift();state.redo=[];updateHistory()}
function updateHistory(){const u=!state.undo.length,r=!state.redo.length;el.undo.disabled=el.floatUndo.disabled=u;el.redo.disabled=el.floatRedo.disabled=r}
function undo(){if(!state.undo.length)return;state.redo.push(ctx.getImageData(0,0,el.canvas.width,el.canvas.height));ctx.putImageData(state.undo.pop(),0,0);updateHistory()}
function redo(){if(!state.redo.length)return;state.undo.push(ctx.getImageData(0,0,el.canvas.width,el.canvas.height));ctx.putImageData(state.redo.pop(),0,0);updateHistory()}
[el.undo,el.floatUndo].forEach(b=>b.onclick=undo);[el.redo,el.floatRedo].forEach(b=>b.onclick=redo);
el.reset.onclick=()=>{if(!state.original)return;snapshot();ctx.putImageData(state.original,0,0);state.line=[];state.path=[];state.lineConfirmed=false;setTool('line');drawOverlay();say('원본으로 복원했습니다')};
function drawOverlay(){ox.clearRect(0,0,el.overlay.width,el.overlay.height);ox.save();const lw=Math.max(2,2/state.scale);if(state.line.length){ox.beginPath();ox.moveTo(state.line[0].x,state.line[0].y);state.line.slice(1).forEach(p=>ox.lineTo(p.x,p.y));ox.strokeStyle=state.lineConfirmed?'#60ffae':'#57e6ff';ox.lineWidth=lw;ox.stroke();state.line.forEach((p,i)=>{ox.beginPath();ox.arc(p.x,p.y,Math.max(4,5/state.scale),0,Math.PI*2);ox.fillStyle=i===0?'#fff':state.lineConfirmed?'#60ffae':'#57e6ff';ox.fill();ox.strokeStyle='#071014';ox.lineWidth=lw;ox.stroke()})}if(state.path.length>1){ox.beginPath();ox.moveTo(state.path[0].x,state.path[0].y);state.path.slice(1).forEach(p=>ox.lineTo(p.x,p.y));ox.strokeStyle='#ffdf57';ox.lineWidth=Math.max(3,4/state.scale);ox.lineCap='round';ox.lineJoin='round';ox.stroke();ox.beginPath();ox.arc(state.path[0].x,state.path[0].y,Math.max(5,6/state.scale),0,Math.PI*2);ox.fillStyle='#fff';ox.fill()}ox.restore();updateStatus()}
function updateStatus(){if(!state.lineConfirmed)el.status.textContent=`기준선 점 ${state.line.length}개 · 스트레치할 경계를 따라 찍고 ‘기준선 확정’을 누르세요.`;else if(state.path.length<2)el.status.textContent='기준선 확정 · 스트레치 그리기를 선택하고 원하는 길이와 곡선을 직접 그리세요.';else el.status.textContent=`그린 경로 ${Math.round(pathMetrics(state.path).total)}px · 적용하면 이 길이만큼 스트레치됩니다.`}
function setTool(tool){state.tool=tool;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));updateStatus()}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
el.confirmLine.onclick=()=>{if(state.line.length<2)return say('점을 2개 이상 찍어주세요');state.lineConfirmed=true;state.path=[];setTool('pen');drawOverlay()};
el.undoPoint.onclick=()=>{if(state.lineConfirmed){state.lineConfirmed=false;state.path=[];setTool('line')}else state.line.pop();drawOverlay()};
el.clearPath.onclick=()=>{state.path=[];drawOverlay()};
function metrics(points){const seg=[],cum=[0];let total=0;for(let i=1;i<points.length;i++){const d=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);seg.push(d);total+=d;cum.push(total)}return{seg,cum,total}}
function sample(points,m,t){const target=t*m.total;let i=1;while(i<m.cum.length&&m.cum[i]<target)i++;i=Math.min(i,points.length-1);const a=points[i-1],b=points[i],d=m.seg[i-1]||1,u=(target-m.cum[i-1])/d;return{x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u,angle:Math.atan2(b.y-a.y,b.x-a.x)}}
function smoothPath(points,amount){if(points.length<3||amount<=0)return points;let out=points.map(p=>({...p}));const rounds=Math.max(1,Math.round(amount/18));for(let r=0;r<rounds;r++){const n=[out[0]];for(let i=0;i<out.length-1;i++){const a=out[i],b=out[i+1];n.push({x:a.x*.75+b.x*.25,y:a.y*.75+b.y*.25},{x:a.x*.25+b.x*.75,y:a.y*.25+b.y*.75})}n.push(out[out.length-1]);out=n}return out}
function buildStrip(){const m=metrics(state.line),w=Math.max(2,Math.ceil(m.total)),h=Math.max(1,Number(el.thickness.value)),src=ctx.getImageData(0,0,el.canvas.width,el.canvas.height),strip=document.createElement('canvas');strip.width=w;strip.height=h;const sc=strip.getContext('2d'),out=sc.createImageData(w,h);for(let x=0;x<w;x++){const p=sample(state.line,m,w===1?0:x/(w-1)),nx=-Math.sin(p.angle),ny=Math.cos(p.angle);for(let y=0;y<h;y++){const off=y-(h-1)/2,sx=Math.max(0,Math.min(el.canvas.width-1,Math.round(p.x+nx*off))),sy=Math.max(0,Math.min(el.canvas.height-1,Math.round(p.y+ny*off))),si=(sy*el.canvas.width+sx)*4,di=(y*w+x)*4;out.data[di]=src.data[si];out.data[di+1]=src.data[si+1];out.data[di+2]=src.data[si+2];out.data[di+3]=src.data[si+3]}}sc.putImageData(out,0,0);return strip}
function applyStretch(){if(!state.lineConfirmed||state.line.length<2)return say('먼저 기준선을 확정해주세요');if(state.path.length<2)return say('손가락으로 스트레치 경로를 그려주세요');const path=smoothPath(state.path,Number(el.smooth.value)),pm=metrics(path);if(pm.total<5)return say('경로를 더 길게 그려주세요');snapshot();const strip=buildStrip(),spread=Number(el.spread.value)/100,alpha=Number(el.opacity.value)/100,steps=Math.min(900,Math.max(20,Math.ceil(pm.total/2)));ctx.save();ctx.globalAlpha=alpha;ctx.imageSmoothingEnabled=true;for(let i=0;i<steps;i++){const t=i/(steps-1),p=sample(path,pm,t),next=sample(path,pm,Math.min(1,t+1/(steps-1))),stepLen=Math.max(1.5,Math.hypot(next.x-p.x,next.y-p.y)+1),scale=1+(spread-1)*t,width=Math.max(1,strip.width*scale);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle+Math.PI/2);ctx.drawImage(strip,-width/2,-stepLen/2,width,stepLen+1);ctx.restore()}ctx.restore();say('그린 경로만큼 스트레치했습니다')}
el.applyPath.onclick=applyStretch;
function beginGesture(){const p=[...state.pointers.values()];if(p.length<2)return;const a=p[0],b=p[1];state.gesture={dist:Math.hypot(b.x-a.x,b.y-a.y),scale:state.scale,tx:state.tx,ty:state.ty,cx:(a.x+b.x)/2,cy:(a.y+b.y)/2};state.drawing=false}
function updateGesture(){const p=[...state.pointers.values()];if(p.length<2||!state.gesture)return;const a=p[0],b=p[1],cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,d=Math.hypot(b.x-a.x,b.y-a.y),ns=Math.max(.05,Math.min(8,state.gesture.scale*d/state.gesture.dist)),r=el.viewport.getBoundingClientRect(),ix=(state.gesture.cx-r.left-state.gesture.tx)/state.gesture.scale,iy=(state.gesture.cy-r.top-state.gesture.ty)/state.gesture.scale;state.scale=ns;state.tx=cx-r.left-ix*ns;state.ty=cy-r.top-iy*ns;applyTransform();drawOverlay()}
el.viewport.addEventListener('pointerdown',e=>{el.viewport.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){beginGesture();return}if(state.pointers.size>1)return;const p=point(e.clientX,e.clientY);state.lastClient={x:e.clientX,y:e.clientY};if(state.tool==='hand'){state.drawing=true;return}if(!inside(p))return;if(state.tool==='line'){if(state.lineConfirmed)return say('기준선이 확정되었습니다. 마지막 점 삭제로 다시 편집하세요');state.line.push(p);drawOverlay();return}if(state.tool==='pen'){if(!state.lineConfirmed)return say('먼저 기준선을 확정해주세요');state.path=[p];state.drawing=true;drawOverlay()}});
el.viewport.addEventListener('pointermove',e=>{if(state.pointers.has(e.pointerId))state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size>=2){updateGesture();return}if(!state.drawing)return;if(state.tool==='hand'){state.tx+=e.clientX-state.lastClient.x;state.ty+=e.clientY-state.lastClient.y;state.lastClient={x:e.clientX,y:e.clientY};applyTransform();return}if(state.tool==='pen'){const p=point(e.clientX,e.clientY),last=state.path[state.path.length-1];if(!last||Math.hypot(p.x-last.x,p.y-last.y)>Math.max(2,4/state.scale)){state.path.push(p);drawOverlay()}}});
function end(e){state.pointers.delete(e.pointerId);if(state.pointers.size<2)state.gesture=null;state.drawing=false}
el.viewport.addEventListener('pointerup',end);el.viewport.addEventListener('pointercancel',end);
el.viewport.addEventListener('wheel',e=>{e.preventDefault();const r=el.viewport.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,ix=(mx-state.tx)/state.scale,iy=(my-state.ty)/state.scale;state.scale=Math.max(.05,Math.min(8,state.scale*Math.exp(-e.deltaY*.001)));state.tx=mx-ix*state.scale;state.ty=my-iy*state.scale;applyTransform();drawOverlay()},{passive:false});
async function save(){const blob=await new Promise(r=>el.canvas.toBlob(r,'image/png',1));if(!blob)return;const file=new File([blob],`${state.fileName}-pixel-stretch-${Date.now()}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Pixel Stretch'});return}}catch(e){if(e.name==='AbortError')return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
el.save.onclick=save;el.helpBtn.onclick=()=>el.help.showModal();el.closeHelp.onclick=()=>el.help.close();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));